# Rustfmt configuration
# Symlink to .config/rustfmt/
# See https://github.com/rust-lang/rustfmt/blob/master/Configurations.md for list.

# Most are still unstable, keep an eye on it.

# Make lines a wee-bit shorted. I prever vertical view of long lines.
# width_heuristics takes care of the rest.
max_width = 75

# Use shorthand for initializing fields.
use_field_init_shorthand = true

# Group imports by where they come from. (Still unstable.)
# group_imports = "StdExternalCrate"
